apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-saqcaxka
  janus-idp.io/tekton: go-saqcaxka
  backstage.io/kubernetes-id: go-saqcaxka
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-saqcaxka
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
